In [1]:
import pandas as pd
import numpy as np

### **Задание на повторение материала numpy

Задание 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)

Задание 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
admissible_dimensions = np.array([2, 3, 4, 6])
dim_1 = np.random.choice(admissible_dimensions, 5)
dim_2 = (12 / dim_1).astype(int)
dimensions  = np.vstack([dim_1, dim_2]).T

df={}
for i in range(5):
    np.random.shuffle(a)
    df[i] = a.reshape(dimensions[i]).copy()
    print(df[i])
    
df[0]

[[17 14]
 [16 13]
 [21 19]
 [23 18]
 [22 20]
 [12 15]]
[[19 12]
 [18 22]
 [15 14]
 [17 20]
 [23 13]
 [21 16]]
[[19 21 17]
 [18 12 16]
 [13 23 14]
 [15 20 22]]
[[22 18]
 [12 21]
 [19 14]
 [20 16]
 [13 17]
 [23 15]]
[[16 15]
 [22 19]
 [13 18]
 [12 17]
 [23 20]
 [14 21]]


array([[17, 14],
       [16, 13],
       [21, 19],
       [23, 18],
       [22, 20],
       [12, 15]])

Задание 3. Создать 5 двумерных массивов разной формы из массива a. 
Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
admissible_dimensions = np.array([2, 3, 4, 6])
dim_1 = np.concatenate([np.random.choice(admissible_dimensions, 3), [-1] * 2])
dim_2 = np.concatenate([[-1] * 3, np.random.choice(admissible_dimensions, 2)])
dimensions  = np.vstack([dim_1, dim_2]).T

df={}
for i in range(5):
    np.random.shuffle(a)
    df[i] = a.reshape(dimensions[i]).copy()
    print(df[i])
    
df[0]

[[18 16 17 15 14 20]
 [12 13 19 21 23 22]]
[[12 13]
 [15 21]
 [20 16]
 [23 22]
 [14 18]
 [17 19]]
[[13 18 20]
 [17 15 14]
 [23 16 19]
 [22 12 21]]
[[14 15]
 [21 18]
 [12 20]
 [13 17]
 [22 19]
 [23 16]]
[[15 18 20 21 12 14]
 [17 23 22 16 13 19]]


array([[18, 16, 17, 15, 14, 20],
       [12, 13, 19, 21, 23, 22]])

Задание 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Можно, если не задавать размерность принудительно через reshape, в этом случае вторая размерность равна 1, например:

In [5]:
print(a.shape)
a.reshape(12, 1).shape

(12,)


(12, 1)

Задание 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [6]:
A = np.random.randn(3,4)
print(A)
A.flatten()

[[-3.74695304 -1.54436668 -0.84080851  0.55432331]
 [-1.36521995 -0.20460598 -0.02637693  0.35940354]
 [-0.19421082  2.59319888 -1.57260837 -0.07633283]]


array([-3.74695304, -1.54436668, -0.84080851,  0.55432331, -1.36521995,
       -0.20460598, -0.02637693,  0.35940354, -0.19421082,  2.59319888,
       -1.57260837, -0.07633283])

Задание 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

Разница в размерности:

In [8]:
b = np.reshape(a, (1,10))
print('a.shape: ', a.shape)
print('b.shape: ', b.shape)
b

a.shape:  (10,)
b.shape:  (1, 10)


array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Задание 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [9]:
a = np.zeros((3,2))
b = np.ones((2,2))
c = np.vstack((a,b))
print('c.size: ', c.size)
c

c.size:  10


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

Задание 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [10]:
a = np.arange(0,12)
A = np.reshape(a, (4, 3))
At = A.T
B = np.dot(A,At)

print('Размер матрицы B = ', B.size)
print('Детерминант В = ', np.linalg.det(B))
print('Обратную матрицу вычислить не получится, т.к. детерминант В = 0')

Размер матрицы B =  16
Детерминант В =  0.0
Обратную матрицу вычислить не получится, т.к. детерминант В = 0


Задание 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [11]:
np.random.seed(42)

Задание 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [12]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

Задание 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [13]:
C = c.reshape(4,4)
D = B + C * 10
print('Определитель D = ', np.linalg.det(D))
print('Ранг D = ', np.linalg.matrix_rank(D))

D_inv = np.linalg.inv(D)
print(D_inv)

Определитель D =  -28511999.999999944
Ранг D =  4
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


Задание 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [14]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [15]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

In [16]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [17]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])