In [1]:
import pandas as pd
import numpy as np

### **Задание на повторение материала numpy

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [108]:
a = np.arange(12, 24)

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [646]:
admissible_dimensions = np.array([2, 3, 4, 6])
dim_1 = np.random.choice(admissible_dimensions, 5)
dim_2 = (12 / dim_1).astype(int)
dimensions  = np.vstack([dim_1, dim_2]).T

df = {}
n = 0
for x, y in dimensions:
    np.random.shuffle(a)
    df[n] = a[: y]
    for i in range(1, x):
        df[n] = np.vstack((df[n], a[i * y : (i + 1) * y]))  
    print(df[n])
    n += 1
df[0]

[21 23 17 22 19 13 15 20 12 14 16 18]
[[19 23 14 21]
 [13 18 20 22]
 [16 15 12 17]]
[[18 12 22 20]
 [16 15 14 19]
 [23 21 17 13]]
[[20 17 14 21]
 [22 16 13 15]
 [23 19 12 18]]
[[23 12]
 [13 18]
 [21 19]
 [14 22]
 [20 15]
 [17 16]]


array([23, 12, 13, 18, 21, 19, 14, 22, 20, 15, 17, 16])

3. Создать 5 двумерных массивов разной формы из массива a. 
Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [650]:
admissible_dimensions = np.array([2, 3, 4, 6])
dim_1 = np.concatenate([np.random.choice(admissible_dimensions, 3), [-1] * 2])
dim_2 = np.concatenate([[-1] * 3, np.random.choice(admissible_dimensions, 2)])
dimensions  = np.vstack([dim_1, dim_2]).T

df={}
for i in range(5):
    df[i] = a.reshape(dimensions[i])
    print(df[i])
    
df[0]

[[23 12 13]
 [18 21 19]
 [14 22 20]
 [15 17 16]]
[[23 12 13]
 [18 21 19]
 [14 22 20]
 [15 17 16]]
[[23 12 13 18]
 [21 19 14 22]
 [20 15 17 16]]
[[23 12 13 18 21 19]
 [14 22 20 15 17 16]]
[[23 12]
 [13 18]
 [21 19]
 [14 22]
 [20 15]
 [17 16]]


array([[23, 12, 13],
       [18, 21, 19],
       [14, 22, 20],
       [15, 17, 16]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Можно, если не задавать размерность принудительно через reshape, в этом случае вторая размерность равна 1, например:

In [653]:
print(a.shape)
a.reshape(12, 1).shape

(12,)


(12, 1)

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [663]:
A = np.random.randn(3,4)
print(A)
A.flatten()

[[-0.34866442  1.99017451 -0.61192248 -0.28587983]
 [-0.50056782 -0.544606    0.33637325 -0.71108428]
 [-1.00452935  1.10552628  1.40884278 -1.09760245]]


array([-0.34866442,  1.99017451, -0.61192248, -0.28587983, -0.50056782,
       -0.544606  ,  0.33637325, -0.71108428, -1.00452935,  1.10552628,
        1.40884278, -1.09760245])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [666]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

Разница в размерности:

In [674]:
b = np.reshape(a, (1,10))
print('a.shape: ', a.shape)
print('b.shape: ', b.shape)
b

a.shape:  (10,)
b.shape:  (1, 10)


array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [686]:
a = np.zeros((3,2))
b = np.ones((2,2))
c = np.vstack((a,b))
print('c.size: ', c.size)
c

c.size:  10


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [718]:
a = np.arange(0,12)
A = np.reshape(a, (4, 3))
At = A.T
B = np.dot(A,At)

print('Размер матрицы B = ', B.size)
print('Детерминант В = ', np.linalg.det(B))
print('Обратную матрицу вычислить не получится, т.к. детерминант В = 0')

Размер матрицы B =  16
Детерминант В =  0.0
Обратную матрицу вычислить не получится, т.к. детерминант В = 0


10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [708]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [713]:
c = np.random.randint(0, 16, 16)
c

array([13, 14, 13,  2, 11,  6,  3, 15,  8,  2,  4,  2,  6,  4,  8,  6])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [757]:
C = c.reshape(4,4)
D = B + C * 10
print('Определитель D = ', np.linalg.det(D))
print('Ранг D = ', np.linalg.matrix_rank(D))

D_inv = np.linalg.inv(D)
print(D_inv)

Определитель D =  -185817199.99999955
Ранг D =  4
[[-3.95980566e-04  3.22897988e-06  2.37983351e-02 -1.51975167e-02]
 [ 9.07041975e-03  9.08613411e-03 -3.64048107e-02  1.52011762e-02]
 [-1.23852905e-03 -1.06993325e-02  1.67565758e-02 -2.52183329e-03]
 [-2.95946769e-03  4.56340963e-03 -3.27289401e-03  1.85623290e-03]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [759]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 1., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [764]:
E = np.where(D_inv, B, C)

array([[ 13,  14,  23,   2],
       [ 14,  50,   3, 122],
       [  8,   2, 149,   2],
       [  6, 122,   8, 302]])